from flask import Flask, request, render_template

app = Flask(__name__)

@app.route('/', methods=["GET", "POST"])
def gfg():
    if request.method == "POST":
        # -*- coding: utf-8 -*-
        """SimpleLinear.ipynb

        Automatically generated by Colaboratory.

        Original file is located at
            https://colab.research.google.com/drive/1z2Z2Q8zalbKDpByaRTuWk98RaNCPOq66#scrollTo=v2-pGuVQx-9K
        """

        import pandas as pd
        import numpy as np
        import seaborn as sns
        from matplotlib import pyplot as plt

        
        diabetes = pd.read_csv('diabetes.csv')
        

        feature_cols = ['Pregnancies', 'Insulin', 'BMI',
                        'Age', 'Glucose', 'BloodPressure', 'DiabetesPedigreeFunction']
        X = diabetes[feature_cols]
        y = diabetes.Outcome

        from sklearn.model_selection import train_test_split
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

        from sklearn.linear_model import LogisticRegression
        model = LogisticRegression()
        model.fit(X_train, y_train)

        coefficents = {"Features": ["Intercept"] + feature_cols,
                    "Coefficients":np.concatenate((model.intercept_ ,model.coef_[0]))}

        y_pred = model.predict(X_test)


        Glucose = request.form.get("Glucose")
        Pregnancies= request.form.get("Pregnancies")
        BP= request.form.get("BP")
        Skin= request.form.get("Skin")
        Insulin = request.form.get("Insulin")
        BMI= request.form.get("BMI")
        Diabetes= request.form.get("Diabetes")
        Age= request.form.get("Age")

        Xnew = [[Glucose],[Pregnancies],[BP],[Skin],[Insulin],[BMI],[Diabetes],[Age]]

        result = model.predict(Xnew)

        value = result.tolist()


        # getting input

        final=str(value[0])




        return final

    return render_template("form.html")

if __name__=='__main__':
   app.run()
